# Generated by Django 2.2.6 on 2021-03-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField(verbose_name='业务ID')),
                ('tmp_id', models.IntegerField(verbose_name='模版ID')),
                ('inst_id', models.IntegerField(verbose_name='作业ID')),
                ('inst_status', models.BooleanField(verbose_name='作业状态')),
                ('inst_finish', models.BooleanField(verbose_name='是否完成')),
                ('log_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='日志')),
                ('request_id', models.CharField(max_length=128, verbose_name='请求ID')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, verbose_name='ip')),
                ('content', models.CharField(max_length=1024, verbose_name='执行结果')),
            ],
        ),
    ]
