# Generated by Django 2.2.6 on 2021-03-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0003_auto_20210308_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='custom_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='自定义ID'),
        ),
    ]
