# Generated by Django 2.2.6 on 2021-03-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0004_logs_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='inst_id',
            field=models.CharField(max_length=128, verbose_name='作业ID'),
        ),
    ]
