# Generated by Django 2.2.6 on 2021-03-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0005_auto_20210308_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='log_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='日志'),
        ),
    ]
