# Generated by Django 2.2.6 on 2021-03-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0006_auto_20210309_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='inst_finish',
            field=models.IntegerField(default=1, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='history',
            name='inst_status',
            field=models.IntegerField(default=1, verbose_name='作业状态'),
        ),
    ]
