# Generated by Django 2.2.6 on 2021-03-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0008_auto_20210309_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='inst_finish',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
