# Generated by Django 2.2.6 on 2021-03-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0009_auto_20210309_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='content',
            field=models.CharField(max_length=2048, verbose_name='执行结果'),
        ),
    ]
