# Generated by Django 2.2.6 on 2021-03-18 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, verbose_name='IP')),
                ('file_list', models.TextField(blank=True, null=True, verbose_name='文件列表')),
                ('file_count', models.IntegerField(default=0, verbose_name='文件数量')),
                ('file_size', models.CharField(default='0', max_length=32, verbose_name='文件大小')),
                ('backup_time', models.DateTimeField(default=datetime.datetime(2021, 3, 18, 15, 55, 30, 166235), verbose_name='备份时间')),
                ('backup_person', models.CharField(max_length=32, verbose_name='备份人')),
                ('job_link', models.TextField(blank=True, null=True, verbose_name='JOB链接')),
            ],
        ),
    ]
