"""
Django settings for operate_manage_platform project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+5!*v&uh5n3xvx-&5!_o*y94z=yu2lrd=8(cw#$(ph9a-xc@9x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
    "app",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # oracle缓存中间件
    'app.utils.middleware.oracle_cache.OracleCacheMiddleware',
]

ROOT_URLCONF = 'operate_manage_platform.urls'
print(os.path.join(BASE_DIR, "static"))
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'static', 'dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'operate_manage_platform.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static', 'dist', 'static')
]

try:
    from .local_settings import *
except ImportError:
    pass

# 上报密钥
REPORT_APIKEY = ''
# 上报地址
REPORT_HTTP_URL = 'http://15.83.120.30:80'
# 上报接口
# 资源配置数据上报
RESOURCE_PUSH = '/api/v2/resource/push_batch'
# 机房环境运行指标数据上报接口
PUSH_ROOM = '/api/v2/env/push/room'
# 服务器监测总体情况上报接口
PUSH_SERVE = '/api/v2/env/push/serve'
# 服务器指标上报接口
PUSH_SERVE_METRIC = '/api/v2/env/push/serve/metric'
# 软件实例运行指标
PUSH_SOFTWARE = '/api/v2/env/push/software'
# 警务微信轻应用运行监控指标
PUSH_WECHAT_MONITOR = '/wechat/v1/monitor/keepAlive'
# 故障告警数据
PUSH_ALERT = '/api/v2/alert/push'

# 注册oralce 请求路径 eg: /api/test
ORACLE_PATH_LIST = (
    '/api/vnetwork/fetch_network_run_list',
    '/api/vnetwork/fetch_network_perf_list',
    '/api/vnetwork/fetch_network_avg_list',
    '/api/vnetwork/fetch_network_link_list',
    '/api/vnetwork/fetch_hardware_resource_list',
    '/api/vnetwork/fetch_room_situation_list',
    '/api/dataoverview/get_data_source',
    '/api/dataoverview/fetch_alarm_record_list',
    '/api/v_network/fetch_alarm_disposition_list',
)
# oracle数据缓存时间 1小时
ORACLE_CACHE_TIMEOUT = 60 * 60

ORACLE_DATA_BASE_NAME = None